services:
  eliza:
    platform: linux/amd64
    command: ["pnpm", "start", "--character=./characters/eliza.character.json"]
    image: ghcr.io/ningxzx/matrix-eliza:f3f50265bc6ca22f2daca9ddf8a8a10508f9768b@sha256:a8e7aac89f8f779d3e2389e5a273cfa04ca75ed779d62746fba8661804680494
    stdin_open: true
    tty: true
    volumes:
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=sk-RFajRhKp5BukHv6MzCZtUTl2MkOTkG0hZLgdoT4Kjefy99NL
      - OPENAI_API_URL= https://api.feidaapi.com/v1
      - DISCORD_APPLICATION_ID=
      - DISCORD_API_TOKEN=
      - REDPILL_API_KEY=
      - REDPILL_MODEL=
      - ELEVENLABS_XI_API_KEY=
      - ELEVENLABS_MODEL_ID=eleven_multilingual_v2
      - ELEVENLABS_VOICE_ID=21m00Tcm4TlvDq8ikWAM
      - ELEVENLABS_VOICE_STABILITY=0.5
      - ELEVENLABS_VOICE_SIMILARITY_BOOST=0.9
      - ELEVENLABS_VOICE_STYLE=0.66
      - ELEVENLABS_VOICE_USE_SPEAKER_BOOST=false
      - ELEVENLABS_OPTIMIZE_STREAMING_LATENCY=4
      - ELEVENLABS_OUTPUT_FORMAT=pcm_16000
      - SOL_ADDRESS=So11111111111111111111111111111111111111112
      - SLIPPAGE=1
      - SOLANA_RPC_URL=https://api.mainnet-beta.solana.com
      - HELIUS_API_KEY=
      - SERVER_PORT=3000
    ports:
      - "3000:3000"
    restart: always
